name: CI Pipeline (Cypress + SonarQube)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  cypress-and-sonarqube:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed for SonarQube analysis

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Make Cypress binary executable
      - name: Make Cypress binary executable
        run: chmod +x node_modules/.bin/cypress

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/register.cy.js,cypress/e2e/login.cy.js,cypress/e2e/create_patient.cy.js"

      # Upload Cypress screenshots if tests fail
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
