name: Cypress Tests

# When to run this workflow
on:
  push:
    branches: [ "main" ]    # Runs on push to main branch
  pull_request:
    branches: [ "main" ]    # Runs on PR to main branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest   # GitHub provides Linux VM

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Make Cypress binary executable
        run: chmod +x node_modules/.bin/cypress

      # Step 4: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/register.cy.js,cypress/e2e/login.cy.js,cypress/e2e/create_patient.cy.js"

      # (Optional) Upload screenshots if tests fail
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # (Optional) Upload Cypress videos always
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
